[phases.setup]
cmds = ["curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci", "npm run build"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"